<?php

namespace Cocorico\CoreBundle\Repository;

/**
 * CategoryProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryProductRepository extends \Doctrine\ORM\EntityRepository
{
}
